[package]
name = "plugins-example"
version = "0.1.0"
authors = ["Rasmus KildevÃ¦ld <rasmuskildevaeld@gmail.com>"]

[dependencies]
plugins = { path = "../plugins" }

libloading = "0.5.0"
uuid = { version = "0.7", features = ["v4", "serde"] }